---
deployment:
  tasks:
    # 1ï¸âƒ£ Set lokasi deploy
    - export DEPLOYPATH=/home/teknonu1/public_html/sibita.teknonusa.it.com

    # 2ï¸âƒ£ Pastikan direktori tujuan ada
    - /bin/mkdir -p $DEPLOYPATH

    # 3ï¸âƒ£ Bersihkan file lama dan copy file baru
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R * $DEPLOYPATH/

    # 4ï¸âƒ£ Aktifkan virtual environment Node.js
    - source /home/teknonu1/nodevenv/public_html/sibita.teknonusa.it.com/22/bin/activate && cd $DEPLOYPATH

    # 5ï¸âƒ£ Hentikan proses Node.js yang sedang berjalan (jika ada)
    - echo "ðŸ›‘ Stopping existing Node.js process (if any)..."
    - pkill -f "node dist/main-dev.js" || true

    # 6ï¸âƒ£ Install dependencies
    - npm install

    # 7ï¸âƒ£ Build TypeScript
    - npm run build

    # 8ï¸âƒ£ Jalankan migration jika diperlukan
    - npx sequelize-cli db:migrate || true

    # 9ï¸âƒ£ Jalankan ulang aplikasi
    - echo "ðŸš€ Starting Node.js app..."
    - nohup node dist/main-dev.js > app.log 2>&1 &
