---
deployment:
  tasks:
    # 1. Set lokasi deploy
    - export DEPLOYPATH=/home/teknonu1/public_html/sibita.teknonusa.it.com

    # 2. Pastikan direktori tujuan ada
    - /bin/mkdir -p $DEPLOYPATH

    # 3. Bersihkan file lama dan copy file baru
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R * $DEPLOYPATH/

    # # Step 3: Aktifkan virtual environment Node.js
    - source /home/teknonu1/nodevenv/public_html/sibita.teknonusa.it.com/22/bin/activate && cd $DEPLOYPATH

    # # Step 4: Install dependencies
    - npm install

    # # Step 5: Build TypeScript
    - npm run build

    # # Step 6: Jalankan migration jika diperlukan
    - npx sequelize-cli db:migrate
